Upgrade flutter_local_notifications to 17.2.4 (fixes bigLargeIcon ambiguity bug)
- 15.x and 16.x had Java compilation error: 'reference to bigLargeIcon is ambiguous'
- 17.2.4 has the fix and is compatible with Flutter 3.24.5
- Also upgrade timezone to ^0.9.4 (required by 17.x)